baseURL = "https://quirky-archimedes-f0b2c0.netlify.com/"
languageCode = "fr-FR"
theme = "jeanrazous"
[params]
description = "Jean razous, psychtopraticien en analyse transactionnelle, systémie et psychothérapie corporelle vous accueille à son cabinet de Lyon 6"
title = "Jean Razous, cabinet de psychothérapies"
