---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: data/paramsite.json
  label: Configuration
- type: directory
  path: content/presentation
  label: Presentation
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/publications
  label: Publications
  create: all
  match: "**/*"
upload_dir: https://res.cloudinary.com/{{ CLOUD_NAME }}/image/upload
public_path: ''
front_matter_path: https://res.cloudinary.com/dpjfqut00/w_800
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
